### ISSUE TITLE
该类型消息暂不支持查看

### ISSUE THREAD

**Issue by Fsyxr** [Agnes4m/nonebot_plugin_poke#2]
![image](https://github.com/Agnes4m/nonebot_plugin_poke/assets/85301551/08ae41c2-9f85-4d94-b27c-ad95b207bf44)
默认配置,使用pip安装

**Comment by Agnes4m** [comment]
1，确保你的cq端不是手表协议什么的，他们无法触发正常消息和图片以外的任何事件。
2，如果是apad协议，那么请更新最新协议8.9.63，否则会稍微有点奇怪的问题(其他例如无法触发私聊等等)
3，如果都不是，把你的cq端和nb端输出都截图看看

**Comment by Fsyxr** [comment]
![image](https://github.com/Agnes4m/nonebot_plugin_poke/assets/85301551/022d433d-957d-4545-af19-6b75cb874eb8)
![image](https://github.com/Agnes4m/nonebot_plugin_poke/assets/85301551/b7598cba-8f0a-4441-bf8e-ba6e200c9f56)

**Comment by Agnes4m** [comment]
已更新0.1.0
