### ISSUE TITLE
只能反击戳,无法发图

### ISSUE THREAD

**Issue by Fsyxr** [Agnes4m/nonebot_plugin_poke#4]
![image](https://github.com/Agnes4m/nonebot_plugin_poke/assets/85301551/d42a3d83-d5c2-4ccb-941f-ef2a58829c46)
![image](https://github.com/Agnes4m/nonebot_plugin_poke/assets/85301551/c6f6ae44-e83d-45e9-a191-6e697f0ff1dc)
![image](https://github.com/Agnes4m/nonebot_plugin_poke/assets/85301551/015ecf9f-ab3e-4013-a3d6-d4d6984546ed)
这个配置应该是随机在pic里面抽一张图吧,实际只能反击戳

**Comment by Agnes4m** [comment]
把冒号注释删了就可以了
